# Generated by Django 4.0 on 2021-12-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='add_datetime',
            new_name='add_timestamp',
        ),
        migrations.AddField(
            model_name='basket',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
